### ISSUE TITLE
Improve build process

### ISSUE THREAD

**Issue by chrislovecnm** [rootfs/snapshot#25]
We are having issues getting the dependencies setup to build the project correctly.  Do we have a process to pull the correct dependencies and build the controller(s)?

**Comment by tsmetana** [comment]
Hello, we have merged the snapshot code into [kubernetes-incubator/external-storage](https://github.com/kubernetes-incubator/external-storage/) and the development continues there. So please report any issues against that repository. It's true we were running into various problems when updating the vendor dependencies and it has to be fixed.

**Comment by chrislovecnm** [comment]
Yep, please update readme or delete this project
